### ISSUE TITLE
イベントのソート機能がほしい

### ISSUE THREAD

**Issue by zwihanderAI** [mstdn-workers/OffDoon#20]
現在
・イベント作成順(降順)

提案：
・回答締め切りが近い順 / 遠い順
・開催日が近い順 / 遠い順
など？

**Comment by pumpCurry** [comment]
引数を受け取るようにして、受け取れない情報を排除するために、
バリデーションで除染する実装をおススメ。
特に、渡された直値をsql式にぶち込むようにすると事故る
`order= {asc|desc}`
`genre= 例として数字のみ`
とかにしておくと安全かと。この時、渡された引数をsql構文にコピーする実装は
絶対にしてはならんとおもう

文字列の配列か、連想配列の配列を定義しておいて、カラム名をそこから取り出すか、
ActiveRecord(ORM)の関係がめんどくさいのであれば、case文で分岐かな。
連想配列にデフォルト昇順降順を定義しておくと、asc/desc指定漏れまたは
あえて指定しないができるので良いとおもう
ついでなにも指定しなかったときの定義(0番目)があれば、もっと楽になれそう。
