### ISSUE TITLE
要望：イベントの並び順のデフォルト値は開催日の早い順だとうれしい

### ISSUE THREAD

**Issue by yakumo-saki** [mstdn-workers/OffDoon#22]
イベントを作った時は、丼に通知が流れると思うので新しいイベントの捕捉は
そっちでまかなえるかなぁと。
だと仮定すると、日時順がデフォルトだと嬉しい。

## 補足
ユースケースとしては、ふらっとOffDoonを見に行って直近のイベント何かあるかなー。
っていう探し方をしていました。

**Comment by rinSouma** [comment]
ソート機能があるのでそちらで対応してください
個人的な美学としては新着優先です
