### ISSUE TITLE
オフ会カレンダー経由でアクセス出来ない

### ISSUE THREAD

**Issue by Corvus400** [mstdn-workers/OffDoon#25]
カレンダーに登録される以下のようなアドレスからアクセスしようとしても、どのイベントも「404 Not Found」になる

https://smrin.net/offdoon/home/9

**Comment by Corvus400** [comment]
- その後、Googleカレンダーではリダイレクトされてアクセスできる事を確認しました。
- 普段SプランナーというGalaxyのプリインストールカレンダーアプリを使っていますが、そちらで起こる現象になります。

**Comment by rinSouma** [comment]
URL大文字小文字区別しているので…
OffDoonの部分だけどっちでもいけるようにしますた
