### ISSUE TITLE
ログインしようとすると 無効なリダイレクトURLです

### ISSUE THREAD

**Issue by yakumo-saki** [mstdn-workers/OffDoon#5]
## 再現手順
1. ログインボタンを押下する
2. ただしいアカウントを入力する
3. （丼にリダイレクトされて、無効なリダイレクトURLです。と表示される）

※ この再現手順は怪しいです。

**Comment by rinSouma** [comment]
DBのクライアントキー削除したら直りました
原因は…わからないです…
キーが無効になっていた？？
